Repository TripComeTrue/TripComeTrue_FE, pull requests merged in 2024-01, with the labels that each got.

#10 style: Title 공통 컴포넌트 추가
  src/components/common/Title/Title.styles.ts
  src/components/common/Title/Title.tsx
  src/components/common/Title/Title.types.ts
  src/components/common/index.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: 🎨 Style

#14 feat: Text 공통 컴포넌트 제작
  src/components/common/Text/Text.styles.ts
  src/components/common/Text/Text.tsx
  src/components/common/Text/Text.types.ts
  src/components/common/Title/Title.styles.ts
  src/components/common/Title/Title.tsx
  src/components/common/Title/Title.types.ts
  src/components/common/index.ts
Labels: 🎨 Style

#17 feat: Button 컴포넌트 수정
  public/images/trip.svg
  public/images/trip_active.svg
  src/components/common/Button/Button.types.ts
  src/components/common/Button/index.ts
  src/components/common/TabBar/TabBar.styles.ts
  src/components/common/TabBar/TabBar.tsx
  src/components/common/index.ts
Labels: 🎨 Style

#18 Style: SubTitle, Avatar UI 컴포넌트 제작
  src/components/common/Avatar/Avatar.styles.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Avatar/Avatar.types.ts
  src/components/common/SubTitle/SubTitle.styles.ts
  src/components/common/SubTitle/SubTitle.tsx
  src/components/common/SubTitle/SubTitle.types.ts
  src/components/common/Text/Text.styles.ts
  src/components/common/Text/Text.tsx
  src/components/common/index.ts
  src/styles/index.css
  src/utils/pxToRem.ts
Labels: 🎨 Style

#19 Feat: 여행계획-날짜선택 페이지 퍼블리싱
  package-lock.json
  package.json
  src/components/Trip/TripPlan/TripPlanCountry/TripPlanCountry.styles.ts
  src/components/Trip/TripPlan/TripPlanCountry/TripPlanCountry.tsx
  src/components/Trip/TripPlan/TripPlanDate/DatePickerStyles.css
  src/components/Trip/TripPlan/TripPlanDate/TripPlanDate.styles.ts
  src/components/Trip/TripPlan/TripPlanDate/TripPlanDate.tsx
  src/pages/Trip/TripPlan/TripPlan.tsx
  src/pages/Trip/index.ts
  yarn.lock
Labels: 🎨 Style

#22 feat: 로그인 / 회원가입 페이지 퍼블리싱
  public/images/validate_icon.png
  public/images/yanolja_black.svg
  public/images/yanolja_white.svg
  src/App.tsx
  src/components/auth/SignInBtns/SignInBtns.styles.ts
  src/components/auth/SignInBtns/SignInBtns.type.ts
  src/components/auth/SignInEmailForm/SignInEmailForm.styles.ts
  src/components/auth/SignInEmailForm/SignInEmailForm.tsx
  src/components/auth/SignInLinks/SignInLinks.tsx
  src/components/auth/SignUpAgreeChk/SignUpAgreeChk.styles.ts
  src/components/auth/SignUpAgreeChk/SignUpAgreeChk.tsx
  src/components/auth/SignUpForm/SignUpForm.tsx
  src/components/auth/SignUpForm/SignUpForm.types.ts
  src/components/common/TextField/EmailInput/EmailInput.tsx
  src/components/common/TextField/EmailInput/EmailInput.types.ts
  src/components/common/TextField/PasswordInput/PasswordInput.tsx
  src/components/common/TextField/PasswordInput/PasswordInput.types.ts
  src/components/common/TextField/TextField.styles.ts
Labels: 🎨 Style

#27 feat: home 페이지 퍼블리싱 (2차 복구+코드리뷰 반영본)
  .eslintrc.cjs
  public/bangkok.png
  public/busan.jpeg
  public/danag.png
  public/jeju.jpeg
  public/osaka.png
  public/starFill.svg
  public/store.svg
  public/tokyo.png
  src/App.tsx
  src/components/Home/HomeCreator/HomeCreator.styles.ts
  src/components/Home/HomeCreator/HomeCreator.tsx
  src/components/Home/HomeCreator/HomeCreator.types.ts
  src/components/Home/HomeCreator/HomeCreatorPost.tsx
  src/components/Home/HomeHotplace/HomeHotplace.styles.ts
  src/components/Home/HomeHotplace/HomeHotplace.tsx
  src/components/Home/HomeHotplace/HomeHotplace.types.ts
  src/components/Home/HomeSearch/HomeSearch.styles.ts
  src/components/Home/HomeSearch/HomeSearch.tsx
  src/components/Home/HomeShorts/HomeShorts.styles.ts
  src/components/Home/HomeShorts/HomeShorts.tsx
  src/components/Home/HomeShorts/HomeShorts.types.ts
  src/components/Home/index.tsx
  src/components/common/SubTitle/SubTitle.types.ts
  src/components/common/Text/Text.types.ts
  src/components/layout/DashBoard/DashBoard.styles.ts
  src/pages/Home/Home.tsx
  src/pages/Main/Home.tsx
  src/styles/fonts/Mundial-Demibold.ttf
  src/styles/index.css
  yarn.lock
Labels: 🎨 Style

#26 feat: 로그인 / 회원가입 기능 구현(1차)
  package.json
  src/App.tsx
  src/components/auth/SignInBtns/SignInBtns.styles.ts
  src/components/auth/SignInBtns/SignInBtns.tsx
  src/components/auth/SignInEmailForm/SignEmailForm.types.ts
  src/components/auth/SignInEmailForm/SignInEmailForm.styles.ts
  src/components/auth/SignInEmailForm/SignInEmailForm.tsx
  src/components/auth/SignInLinks/SignInLinks.styles.ts
  src/components/auth/SignInLinks/SignInLinks.tsx
  src/components/auth/SignInModal/SignInModal.styles.ts
  src/components/auth/SignUpAgreeChk/SignUpAgreeChk.tsx
  src/components/auth/SignUpAgreeChk/SignUpAgreeChk.types.ts
  src/components/auth/SignUpAgreeChk/SignUpAgreeChkBox.tsx
  src/components/auth/SignUpAgreeChk/SignUpAgreeChkBox.types.ts
  src/components/auth/SignUpAgreeChk/SignUpAgreeModal.styles.ts
  src/components/auth/SignUpAgreeChk/SignUpAgreeModal.tsx
  src/components/auth/SignUpAgreeChk/SignUpAgreeModal.types.ts
  src/components/auth/SignUpForm/SignUpForm.tsx
  src/components/auth/SignUpForm/SignUpForm.types.ts
  src/components/auth/SignUpPolicy/SignUpLocationAgree.tsx
  src/components/auth/SignUpPolicy/SignUpMarketingAgree.tsx
  src/components/auth/SignUpPolicy/SignUpPolicy.utils.ts
  src/components/auth/SignUpPolicy/SignUpPolicyAgree.tsx
  src/components/auth/SignUpPolicy/SignUpPrivacyAgree.tsx
  src/components/auth/index.ts
  src/components/common/Modal/Modal.styles.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/Modal.types.ts
  src/components/common/TextField/EmailInput/EmailInput.tsx
  src/components/common/TextField/EmailInput/EmailInput.types.ts
  src/components/common/index.ts
  src/constants/maxAge.ts
  src/hooks/Auth/useLoginCheck.ts
  src/pages/Auth/SignIn.tsx
  src/pages/Auth/SignInEmail.tsx
  src/pages/Auth/SignUp.tsx
  src/pages/Auth/SignUpAgree.tsx
  src/pages/Auth/Social.tsx
  src/pages/Auth/index.ts
  src/utils/cookie.ts
  yarn.lock
Labels: ✨ Feature

#31 style: 북마크, 선택 모달 컴포넌트 생성
  public/images/kakao_logo.png
  public/images/share-link.svg
  src/components/auth/SignInModal/SignInModal.styles.ts
  src/components/common/Bookmark/Bookmark.styles.ts
  src/components/common/Bookmark/Bookmark.tsx
  src/components/common/Bookmark/Bookmark.types.ts
  src/components/common/Modal/Modal.styles.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/Modal.types.ts
  src/components/common/Modal/SelectModal.styles.ts
  src/components/common/Modal/SelectModal.tsx
  src/components/common/Modal/SelectModal.types.ts
  src/components/common/Share/Share.styles.ts
  src/components/common/Share/Share.tsx
  src/components/common/Share/Share.types.ts
  src/components/common/TabBar/TabBar.styles.ts
  src/components/common/index.ts
  src/hooks/common/useModal.ts
  src/pages/Auth/SignInEmail.tsx
  src/pages/Auth/SignUp.tsx
  src/styles/common.ts
Labels: 🎨 Style

#36 style: 여행지 상세 부분 UI 공통 컴포넌트화
  public/message.svg
  src/components/Home/HomeCreator/HomeCreator.styles.ts
  src/components/Home/HomeCreator/HomeCreator.tsx
  src/components/Home/HomeCreator/HomeCreatorPost.tsx
  src/components/Home/HomeHotplace/HomeHotplace.styles.ts
  src/components/Home/HomeHotplace/HomeHotplace.tsx
  src/components/Home/HomeMD/HomeMD.tsx
  src/components/Home/HomeMD/HomeMD.types.ts
  src/components/Home/HomeMD/HomeMDChoice.tsx
  src/components/common/Spots/Spots.style.ts
  src/components/common/Spots/Spots.tsx
  src/components/common/Spots/Spots.types.ts
  src/components/common/Spots/SpotsSwiper.tsx
Labels: 🎨 Style

#32 style: 여행 일정 메인 UI 작업
  public/images/bookMark.svg
  public/images/comment.svg
  public/images/dollar.svg
  public/images/magnifier.svg
  public/images/mark.svg
  public/images/plus.svg
  public/images/schedule.svg
  public/images/shower.svg
  public/images/tripLogo.svg
  public/images/write.svg
  src/components/Trip/TripHome/CreatorCarousel/CreatorCarousel.styles.ts
  src/components/Trip/TripHome/CreatorCarousel/CreatorCarousel.tsx
  src/components/Trip/TripHome/FloatingButton/FloatingButton.styles.ts
  src/components/Trip/TripHome/FloatingButton/FloatingButton.tsx
  src/components/Trip/TripHome/ShortCard/ShortCard.styles.ts
  src/components/Trip/TripHome/ShortCard/ShortCard.tsx
  src/components/Trip/TripHome/ShortCarousel/ShortCarousel.styles.ts
  src/components/Trip/TripHome/ShortCarousel/ShortCarousel.tsx
  src/components/Trip/TripHome/TripCard/TripCard.styles.ts
  src/components/Trip/TripHome/TripCard/TripCard.tsx
  src/components/Trip/TripHome/TripCard/TripCard.types.ts
  src/components/Trip/TripHome/TripCarousel/TripCarousel.styles.ts
  src/components/Trip/TripHome/TripCarousel/TripCarousel.tsx
  src/components/Trip/TripHome/TripCarousel/TripCarousel.types.ts
  src/components/Trip/TripHome/TripHomeBody/TripHomeBody.styles.ts
  src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx
  src/components/Trip/TripHome/TripHomeHeader/TripHomeHeader.styles.ts
  src/components/Trip/TripHome/TripHomeHeader/TripHomeHeader.tsx
  src/components/Trip/TripHome/index.ts
  src/components/Trip/index.ts
  src/components/common/Bookmark/Bookmark.styles.ts
  src/components/common/TabBar/TabBar.styles.ts
  src/components/common/TabBar/TabBar.tsx
  src/components/common/TabBar/TabBar.types.ts
  src/components/common/index.ts
  src/components/layout/DashBoard/DashBoard.styles.ts
  src/hooks/common/useClickOutside.ts
  src/pages/Trip/TripHome/TripHome.styles.ts
  src/pages/Trip/TripHome/TripHome.tsx
  src/styles/index.css
Labels: 🎨 Style

#38 style: 홈 > 전체 도시 페이지용 컴포넌트 제작
  public/images/flight-icon.svg
  public/images/go-arrow.svg
  src/App.tsx
  src/components/Home/HomeAllCity/HomeAllCity.styles.ts
  src/components/Home/HomeAllCity/HomeAllCity.tsx
  src/components/Home/HomeAllCity/HomeAllCity.types.ts
  src/components/Home/HomeAllCity/HomeCities.styles.ts
  src/components/Home/HomeAllCity/HomeCities.tsx
  src/components/Home/HomeAllCity/HomeCities.types.ts
  src/components/Home/HomeAllCity/HomeCountryItem.styles.ts
  src/components/Home/HomeAllCity/HomeCountryItem.tsx
  src/components/Home/HomeAllCity/HomeCountryItem.types.ts
  src/components/Home/HomeAllCity/HomeKoreaCityItem.tsx
  src/components/Home/HomeAllCity/HomeKoreaCityItem.types.ts
  src/components/Home/index.tsx
  src/components/common/Navigation/SimpleNav.styles.ts
  src/components/common/TextField/EmailInput/EmailInput.tsx
  src/constants/city.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: 🎨 Style

#45 Feat: 여행피드(여행 계획) 페이지 퍼블리싱 - 2차
  package.json
  public/images/delete.svg
  src/App.tsx
  src/components/Trip/TripPlan/TripPlanCity/CityListModal/CityListModal.styles.ts
  src/components/Trip/TripPlan/TripPlanCity/CityListModal/CityListModal.tsx
  src/components/Trip/TripPlan/TripPlanCity/CityListModal/CityListModal.types.ts
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCity.styles.ts
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCity.tsx
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCity.types.ts
  src/components/Trip/TripPlan/TripPlanCommon/TripPlanCommon.styles.ts
  src/components/Trip/TripPlan/TripPlanCommon/TripPlanCommon.tsx
  src/components/Trip/TripPlan/TripPlanCountry/TripPlanCountry.styles.ts
  src/components/Trip/TripPlan/TripPlanCountry/TripPlanCountry.tsx
  src/components/Trip/TripPlan/TripPlanCountry/TripPlanCountry.types.ts
  src/components/Trip/TripPlan/TripPlanCountry/constants/CountryData.ts
  src/components/Trip/TripPlan/TripPlanCountry/constants/china.png
  src/components/Trip/TripPlan/TripPlanCountry/constants/france.png
  src/components/Trip/TripPlan/TripPlanCountry/constants/japan.png
  src/components/Trip/TripPlan/TripPlanCountry/constants/uk.png
  src/components/Trip/TripPlan/TripPlanDate/DatePickerStyles.css
  src/components/Trip/TripPlan/TripPlanDate/TripPlanDate.styles.ts
  src/components/Trip/TripPlan/TripPlanDate/TripPlanDate.tsx
  src/components/Trip/TripPlan/TripPlanDate/TripPlanDate.types.ts
  src/components/Trip/TripPlan/index.ts
  src/pages/Trip/TripPlan/TripPlan.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Style

#41 feat: pdf 다운로드 기능구현 및 퍼블리싱 (1차)
  package.json
  public/images/line-review01.jpg
  public/images/line-review02.jpg
  public/images/line-review03.jpg
  public/images/map-pin.png
  public/images/maybin-review01.jpg
  public/images/maybin-review02.jpg
  public/images/maybin-review03.jpg
  src/components/Trip/TripDownload/TripDownloadDoc.styles.ts
  src/components/Trip/TripDownload/TripDownloadDoc.tsx
  src/components/Trip/TripDownload/TripDownloadDoc.types.ts
  yarn.lock
Labels: ✨ Feature

#43 style: 여행 일정 목록 UI 작업
  src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx
  src/components/Trip/TripList/CardList/CardList.styles.ts
  src/components/Trip/TripList/CardList/CardList.tsx
  src/components/Trip/TripList/index.ts
  src/components/Trip/index.ts
  src/components/common/Navigation/SimpleNav.styles.ts
  src/components/common/SubTitle/SubTitle.styles.ts
  src/pages/Trip/TripList/TripList.styles.ts
  src/pages/Trip/TripList/TripList.tsx
  src/styles/theme.ts
Labels: 🎨 Style

#56 style: 검색 페이지 라우팅 및 UI (1차)
  public/starFill.svg
  src/App.tsx
  src/components/Creator/CreatorDetail/CreatorDetail.styles.ts
  src/components/Creator/CreatorDetail/CreatorDetail.tsx
  src/components/Creator/CreatorInfo/CreatorInfo.styles.ts
  src/components/Creator/CreatorInfo/CreatorInfo.tsx
  src/components/Creator/CreatorInfo/CreatorInfo.types.ts
  src/components/Creator/CreatorMore/CreateMore.types.ts
  src/components/Creator/CreatorMore/CreatorMore.styles.ts
  src/components/Creator/CreatorMore/CreatorMore.tsx
  src/components/Creator/CreatorProfile/CreatorProfile.styles.ts
  src/components/Creator/CreatorProfile/CreatorProfile.tsx
  src/components/Creator/index.tsx
  src/components/Home/HomeHotplace/HomeHotplace.tsx
  src/components/Home/HomeSearch/HomeSearch.styles.ts
  src/components/Home/HomeSearch/HomeSearch.tsx
  src/components/Search/SearchCity/SearchCity.tsx
  src/components/Search/SearchCreator/SearchCreator.tsx
  src/components/Search/SearchKeyword/SearchKeyword.styles.ts
  src/components/Search/SearchKeyword/SearchKeyword.tsx
  src/components/Search/SearchSpot/SearchSpot.tsx
  src/components/Search/index.ts
  src/components/common/Creator/Creator.styles.ts
  src/components/common/Creator/Creator.types.ts
  src/components/common/index.ts
  src/pages/Creator/Creator.tsx
  src/pages/Creator/CreatorDetails.tsx
  src/pages/Search/Search.styles.ts
  src/pages/Search/Search.tsx
  src/pages/Search/Search.types.ts
  src/pages/Search/SearchAll.tsx
  src/pages/Search/SearchCity.tsx
  src/pages/Search/SearchCreator.tsx
  src/pages/Search/SearchSpot.tsx
  src/pages/Search/SearchTag.tsx
Labels: ✨ Feature, 🎨 Style

#51 style: 여행태그종류 모달, 해시태그 등록, 상세피드 헤더 컴포넌트 제작
  src/assets/back-arrow.svg
  src/assets/share.svg
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanHashtags.styles.ts
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanHashtags.tsx
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanHashtags.types.ts
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanTagModal.styles.ts
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanTagModal.tsx
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanTagModal.types.ts
  src/components/common/Button/index.ts
  src/components/common/Navigation/FeedNav.styles.ts
  src/components/common/Navigation/FeedNav.tsx
  src/components/common/Navigation/FeedNav.types.ts
  src/components/common/Navigation/SimpleNav.styles.ts
  src/components/common/Navigation/SimpleNav.tsx
  src/components/common/index.ts
  src/constants/hashtags.ts
Labels: 🎨 Style

#53 style: 쇼츠 유튜브 모달 제작
  package.json
  src/components/common/Modal/ShortsModal.styles.ts
  src/components/common/Modal/ShortsModal.tsx
  src/components/common/Modal/ShortsModal.types.ts
  src/components/common/Modal/ShortsModal.utils.ts
  src/components/common/index.ts
  yarn.lock
Labels: 🎨 Style

#54 style: 여행지 상세 피드 레이아웃
  public/defaultPin.svg
  public/infoPhone.svg
  public/infoPin.svg
  public/infoTime.svg
  src/App.tsx
  src/components/DetailFeed/Gallery/Gallery.styles.ts
  src/components/DetailFeed/Gallery/Gallery.tsx
  src/components/DetailFeed/Information/CityInformation.styles.ts
  src/components/DetailFeed/Information/CityInformation.tsx
  src/components/DetailFeed/Information/SpotInformation.styles.ts
  src/components/DetailFeed/Information/SpotInformation.tsx
  src/components/DetailFeed/TopReview/TopReview.styles.ts
  src/components/DetailFeed/TopReview/TopReview.tsx
  src/components/DetailFeed/TopReview/TopReview.types.ts
  src/components/DetailFeed/index.ts
  src/components/Map/Map.styles.ts
  src/components/Map/Map.tsx
  src/constants/DetailFeed/Map.ts
  src/pages/DetailFeed/City/City.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.styles.ts
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
  src/pages/DetailFeed/TripMap.tsx
  src/pages/DetailFeed/index.ts
Labels: 🎨 Style

#62 style: 여행피드(계획 작성 페이지) 퍼블리싱
  package.json
  public/images/speech-bubble.svg
  src/App.tsx
  src/components/DetailFeed/Gallery/Gallery.tsx
  src/components/Trip/TripPlan/TripPlanCity/CityListModal/CityListModal.tsx
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCity.styles.ts
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCity.tsx
  src/components/Trip/TripPlan/TripPlanCommon/TripPlanCommon.tsx
  src/components/Trip/TripPlan/TripPlanCountry/TripPlanCountry.styles.ts
  src/components/Trip/TripPlan/TripPlanCountry/TripPlanCountry.tsx
  src/components/Trip/TripPlan/TripPlanDate/TripPlanDate.tsx
  src/components/Trip/TripPlan/TripPlanDate/TripPlanDate.types.ts
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanGoogleMaps.tsx
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanPosting.styles.ts
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanPosting.tsx
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanPosting.types.ts
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanTagModal.tsx
  src/components/common/Modal/ShortsModal.utils.ts
  yarn.lock
Labels: 🎨 Style

#60 style: 갤러리, 여행지 목록, 쇼츠 목록 페이지, 검색페이지 레이아웃
  public/bookmark.svg
  public/comment.svg
  public/map.svg
  public/polygon.svg
  public/search.svg
  public/searchGreen.svg
  src/App.tsx
  src/components/DetailFeed/Banner/Banner.styles.ts
  src/components/DetailFeed/DetailFeedShorts/DetailFeedShorts.styles.ts
  src/components/DetailFeed/DetailFeedShorts/DetailFeedShorts.tsx
  src/components/DetailFeed/ExchangeRate/ExchangeRate.styles.ts
  src/components/DetailFeed/Filter/Filter.styles.ts
  src/components/DetailFeed/Filter/Filter.tsx
  src/components/DetailFeed/Gallery/Gallery.styles.ts
  src/components/DetailFeed/Gallery/Gallery.tsx
  src/components/DetailFeed/HotPlace/HotPlace.styles.ts
  src/components/DetailFeed/HotPlace/HotPlace.tsx
  src/components/DetailFeed/Information/CityInformation.styles.ts
  src/components/DetailFeed/Information/CityInformation.tsx
  src/components/DetailFeed/Information/SpotInformation.styles.ts
  src/components/DetailFeed/TopReview/TopReview.styles.ts
  src/components/DetailFeed/TopReview/TopReview.tsx
  src/components/DetailFeed/Weather/Weather.styles.ts
  src/components/DetailFeed/index.ts
  src/components/common/Navigation/SpotListNav.styles.ts
  src/components/common/Navigation/SpotListNav.tsx
  src/pages/DetailFeed/City/City.styles.ts
  src/pages/DetailFeed/City/City.tsx
  src/pages/DetailFeed/GalleryList/GalleryList.styles.ts
  src/pages/DetailFeed/GalleryList/GalleryList.tsx
  src/pages/DetailFeed/ShortsList/ShortsList.styles.ts
  src/pages/DetailFeed/ShortsList/ShortsList.tsx
  src/pages/DetailFeed/SpotList/SpotDescription.styles.ts
  src/pages/DetailFeed/SpotList/SpotDescription.tsx
  src/pages/DetailFeed/SpotList/SpotList.styles.ts
  src/pages/DetailFeed/SpotList/SpotList.tsx
  src/pages/DetailFeed/SpotSearch/SpotSearch.styles.ts
  src/pages/DetailFeed/SpotSearch/SpotSearch.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.styles.ts
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
  src/pages/DetailFeed/index.ts
Labels: 🎨 Style

#64 Fix: vercel.json 추가
  vercel.json
Labels: 🐞 BugFix

#67 style: 리뷰 더 보기, 필터 공통 컴포넌트 구현
  package.json
  src/App.tsx
  src/apis/SignIn/index.ts
  src/apis/SignIn/signInType.ts
  src/apis/client.ts
  src/apis/trip-records.ts
  src/components/DetailFeed/SpotReview/SpotReview.styles.ts
  src/components/DetailFeed/SpotReview/SpotReview.tsx
  src/components/DetailFeed/index.ts
  src/components/Trip/TripHome/ShortCard/ShortCard.tsx
  src/components/auth/SignInEmailForm/SignInEmailForm.tsx
  src/components/auth/SignUpForm/SignUpForm.tsx
  src/components/common/Filter/Filter.styles.ts
  src/components/common/Filter/Filter.tsx
  src/components/common/Filter/Filter.types.ts
  src/components/common/ReviewWrite/ReviewWrite.styles.ts
  src/components/common/ReviewWrite/ReviewWrite.tsx
  src/components/common/ReviewWrite/ReviewWrite.types.ts
  src/components/common/TextField/EmailInput/EmailInput.tsx
  src/components/common/index.ts
  src/pages/DetailFeed/ReviewComment/ReviewComment.styles.ts
  src/pages/DetailFeed/ReviewComment/ReviewComment.tsx
  src/pages/DetailFeed/Reviews/Reviews.styles.ts
  src/pages/DetailFeed/Reviews/Reviews.tsx
  src/pages/DetailFeed/SpotReviewWrite/SpotReviewWriteEdit.tsx
  src/pages/DetailFeed/SpotReviewWrite/SpotReviewWriteNew.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
  src/pages/DetailFeed/index.ts
  src/pages/Trip/TripReview/TripReviewEdit.tsx
  src/pages/Trip/TripReview/TripReviewNew.tsx
  src/pages/Trip/TripReviewWrite/TripReviewWriteEdit.tsx
  src/pages/Trip/TripReviewWrite/TripReviewWriteNew.tsx
  src/pages/Trip/index.ts
  yarn.lock
Labels: 🎨 Style

#69 feat: 여행 일정 후기 API 작성
  .eslintrc.cjs
  src/@types/trip-records.types.ts
  src/apis/trip-records.ts
  src/components/Trip/TripHome/TripCard/TripCard.tsx
  src/components/Trip/TripHome/TripCard/TripCard.types.ts
  src/components/Trip/TripHome/TripCarousel/TripCarousel.tsx
  src/components/Trip/TripHome/TripCarousel/TripCarousel.types.ts
  src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx
  src/components/Trip/TripList/CardList/CardList.tsx
  src/components/Trip/TripList/CardList/CardList.types.ts
  src/mocks/handlers.ts
  src/pages/Trip/TripDetail/TripDetail.tsx
  src/pages/Trip/TripList/TripList.tsx
Labels: 📬 API

#71 feat: 여행 메인페이지, 이미지 업로드 API 연결 및 구현
  .eslintrc.cjs
  public/images/averageIcon.svg
  public/images/shower.svg
  src/@types/trip-records.types.ts
  src/App.tsx
  src/apis/images.ts
  src/apis/trip-records.ts
  src/components/Trip/TripDetail/Introduction/Introduction.styles.ts
  src/components/Trip/TripDetail/Introduction/Introduction.tsx
  src/components/Trip/TripDetail/Introduction/Introduction.types.ts
  src/components/Trip/TripDetail/MainCarousel/MainCarousel.tsx
  src/components/Trip/TripDetail/MainCarousel/MainCarousel.types.ts
  src/components/Trip/TripDetail/TripContents/TripContents.tsx
  src/components/Trip/TripDetail/TripContents/TripContents.types.ts
  src/components/Trip/TripDetail/TripDescription/TripDescription.tsx
  src/components/Trip/TripHome/ShortCard/ShortCard.tsx
  src/components/Trip/TripHome/ShortCard/ShortCard.types.ts
  src/components/Trip/TripHome/ShortCarousel/ShortCarousel.tsx
  src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.styles.ts
  src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.tsx
  src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.types.ts
  src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx
  src/components/common/ActionsModal/ActionsModal.styles.ts
  src/components/common/ActionsModal/ActionsModal.tsx
  src/components/common/ActionsModal/ActionsModal.types.ts
  src/components/common/Navigation/SimpleNav.styles.ts
  src/components/common/PlaceReviewCard/PlaceReviewCard.styles.ts
  src/components/common/PlaceReviewCard/PlaceReviewCard.tsx
  src/components/common/PlaceReviewCard/PlaceReviewCardtypes.ts
  src/components/common/Tag/Tag.tsx
  src/components/common/Tag/Tag.types.ts
  src/components/common/TripRecordReviewCard/TripRecordReviewCard.styles.ts
  src/components/common/TripRecordReviewCard/TripRecordReviewCard.tsx
  src/components/common/TripRecordReviewCard/TripRecordReviewCard.types.ts
  src/components/common/index.ts
  src/hooks/common/useDeleteImages.ts
  src/hooks/common/useSubmitImages.ts
  src/hooks/common/useUploadImages.ts
  src/main.tsx
  src/pages/DetailFeed/Reviews/Reviews.styles.ts
  src/pages/DetailFeed/Reviews/Reviews.tsx
  src/pages/Trip/TripDetail/TripDetail.tsx
  src/pages/Trip/TripList/TripList.tsx
Labels: ✨ Feature, 📬 API

#76 refactor: 이미지 업로드 커스텀 훅 수정
  src/hooks/common/useDeleteImages.ts
  src/hooks/common/useSubmitImages.ts
Labels: 🔨 Refactor

#78 feat: 여행지 리뷰 작성, 수정하기 구현
  .eslintrc.cjs
  src/@types/place.ts
  src/App.tsx
  src/apis/client.ts
  src/apis/place.ts
  src/apis/trip-records.ts
  src/components/DetailFeed/PlaceReview/PlaceReview.styles.ts
  src/components/DetailFeed/PlaceReview/PlaceReview.tsx
  src/components/DetailFeed/index.ts
  src/components/common/PlaceReviewCard/PlaceReviewCard.tsx
  src/components/common/ReviewWrite/ReviewWrite.tsx
  src/components/common/ReviewWrite/ReviewWrite.types.ts
  src/pages/DetailFeed/PlaceReviewWrite/PlaceReviewWriteEdit.tsx
  src/pages/DetailFeed/PlaceReviewWrite/PlaceReviewWriteNew.tsx
  src/pages/DetailFeed/Reviews/Reviews.tsx
  src/pages/DetailFeed/SpotReviewWrite/SpotReviewWriteEdit.tsx
  src/pages/DetailFeed/SpotReviewWrite/SpotReviewWriteNew.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
  src/pages/DetailFeed/index.ts
  src/pages/Trip/TripDetail/TripDetail.tsx
  src/utils/formattedDate.ts
Labels: ✨ Feature

#80 style: 여행 후기 작성 / 수정 페이지 및 컴포넌트 제작
  public/images/addtag.png
  public/images/map-mark.svg
  src/App.tsx
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCity.tsx
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCityList.styles.ts
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCityList.types.ts
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCityModal/TripPlanCityModal.styles.ts
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCityModal/TripPlanCityModal.tsx
  src/components/Trip/TripPlan/TripPlanCity/TripPlanCityModal/TripPlanCityModal.types.ts
  src/components/Trip/TripPlan/TripPlanCommon/TripPlanCommon.styles.ts
  src/components/Trip/TripPlan/TripPlanCommon/TripPlanCommon.tsx
  src/components/Trip/TripPlan/TripPlanCommon/TripPlanCommon.types.ts
  src/components/Trip/TripPlan/TripPlanCountry/TripPlanCountry.styles.ts
  src/components/Trip/TripPlan/TripPlanCountry/TripPlanCountry.tsx
  src/components/Trip/TripPlan/TripPlanDate/DatePickerStyles.css
  src/components/Trip/TripPlan/TripPlanDate/TripPlanDate.tsx
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanGoogleMaps.tsx
  src/components/Trip/TripPlan/TripPlanPosting/TripPlanHashtags.tsx
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanGoogleMaps/TripPlanGoogleMaps.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanGoogleMaps/TripPlanGoogleMaps.tsx
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanGoogleMaps/TripPlanGoogleMaps.types.ts
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlan.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlan.tsx
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlan.types.ts
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanUploadImages/TripPlanUploadImages.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanUploadImages/TripPlanUploadImages.tsx
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanUploadImages/TripPlanUploadImages.types.ts
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanUploadMainImages/TripPlanUploadMainImages.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanUploadMainImages/TripPlanUploadMainImages.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddHashtags/TripPlanAddHashtags.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddHashtags/TripPlanAddHashtags.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddHashtags/TripPlanHashtagsList/TripPlanHashtagsList.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddHashtags/TripPlanHashtagsList/TripPlanHashtagsList.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddHashtags/TripPlanHashtagsList/TripPlanHashtagsList.types.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddPlace/TripPlanAddPlace.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddPlace/TripPlanAddPlace.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddPlace/TripPlanAddPlace.types.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddPlace/TripPlanPlaceModal/TripPlanPlaceModal.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddPlace/TripPlanPlaceModal/TripPlanPlaceModal.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddPlace/TripPlanPlaceModal/TripPlanPlaceModal.types.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddTags/TripPlanAddTags.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddTags/TripPlanAddTags.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddTags/TripPlanAddTagsForImage/TripPlanAddTagsForImage.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddTags/TripPlanAddTagsForImage/TripPlanAddTagsForImage.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddTags/TripPlanTagsModal/TripPlanTagsModal.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddTags/TripPlanTagsModal/TripPlanTagsModal.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddTags/TripPlanTagsModal/TripPlanTagsModal.types.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanSetBudget/TripPlanSetBudget.styles.ts
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanSetBudget/TripPlanSetBudget.tsx
  src/components/Trip/TripPlan/index.ts
  src/constants/hashtags.ts
  src/constants/tripBudget.ts
  src/pages/Trip/TripPlan/TripPlan.tsx
  src/pages/Trip/TripPlan/TripPlanReview.tsx
  src/pages/Trip/TripPlan/TripReview.tsx
Labels: ✨ Feature, 🎨 Style

#82 style: 검색 페이지 UI (2차)
  public/searchImg.png
  public/spotCall.svg
  public/spotPing.png
  public/spotTime.svg
  src/App.tsx
  src/components/Search/SearchCity/SearchCity.styles.ts
  src/components/Search/SearchCity/SearchCity.tsx
  src/components/Search/SearchCreator/SearchCreator.styles.ts
  src/components/Search/SearchCreator/SearchCreator.tsx
  src/components/Search/SearchCreator/SearchCreator.types.ts
  src/components/Search/SearchKeyword/SearchKeyword.tsx
  src/components/Search/SearchNon/SearchNon.styles.ts
  src/components/Search/SearchNon/SearchNon.tsx
  src/components/Search/SearchNon/SearchNon.types.ts
  src/components/Search/SearchSpot/SearchSpot.styles.ts
  src/components/Search/SearchSpot/SearchSpot.tsx
  src/components/Search/index.ts
  src/pages/Search/Search.tsx
  src/pages/Search/SearchAll.tsx
  src/pages/Search/SearchCity.tsx
  src/pages/Search/SearchCitys.tsx
  src/pages/Search/SearchCreator.tsx
  src/pages/Search/SearchCreators.tsx
  src/pages/Search/SearchNons.tsx
  src/pages/Search/SearchSpot.tsx
Labels: ✨ Feature, 🎨 Style

#86 feat: 여행 일정 메인페이지 쇼츠 구현 및 검색 링크 연결
  public/images/theme1.jpg
  public/images/theme2.jpg
  public/images/tripMainImage.jpg
  src/@types/trip-records.types.ts
  src/App.tsx
  src/apis/trip-records.ts
  src/components/Trip/TripDetail/Maps/Maps.tsx
  src/components/Trip/TripHome/ShortCard/ShortCard.tsx
  src/components/Trip/TripHome/ShortCard/ShortCard.types.ts
  src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.styles.ts
  src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.tsx
  src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx
  src/components/Trip/TripHome/TripHomeHeader/TripHomeHeader.styles.ts
  src/components/Trip/TripHome/TripHomeHeader/TripHomeHeader.tsx
  src/components/common/TripRecordReviewCard/TripRecordReviewCard.tsx
  src/pages/Trip/TripDetail/TripDetail.tsx
  src/pages/Trip/TripList/TripList.styles.ts
  src/pages/Trip/TripList/TripList.tsx
Labels: ✨ Feature

#88 feat: home API 연결 (1차)
  .eslintrc.cjs
  src/apis/auth.ts
  src/apis/home.ts
  src/apis/search.ts
  src/components/Home/HomeHotplace/HomeHotplace.tsx
  src/components/Home/HomeHotplace/HomeHotplace.types.ts
  src/components/Search/SearchCity/SearchCity.styles.ts
  src/components/Search/SearchCity/SearchCity.tsx
  src/components/Search/SearchCreator/SearchCreator.tsx
  src/components/Search/SearchCreator/SearchCreatorShorts.tsx
  src/components/Search/SearchSpot/SearchSpot.styles.ts
  src/components/Search/SearchSpot/SearchSpot.tsx
  src/components/Search/index.ts
  src/pages/Search/SearchCreators.tsx
Labels: ✨ Feature, 📬 API

#92 feat: 여행 후기 리뷰 작성, 수정하기 구현
  src/App.tsx
  src/apis/trip-records.ts
  src/components/MyPage/MyPageComment/MyPageTripRecordReview.tsx
  src/components/Trip/TripDetail/Maps/Maps.tsx
  src/components/common/ReviewWrite/ReviewWrite.tsx
  src/components/common/TripRecordReviewCard/TripRecordReviewCard.tsx
  src/pages/DetailFeed/PlaceReview/PlaceReviewEdit.tsx
  src/pages/DetailFeed/PlaceReview/PlaceReviewWrite.tsx
  src/pages/DetailFeed/index.ts
  src/pages/Trip/TripDetail/TripDetail.tsx
  src/pages/Trip/TripRecordReview/TripRecordReviewEdit.tsx
  src/pages/Trip/TripRecordReview/TripRecordReviewWrite.tsx
  src/pages/Trip/TripReviewWrite/TripReviewWriteEdit.tsx
  src/pages/Trip/TripReviewWrite/TripReviewWriteNew.tsx
  src/pages/Trip/index.ts
Labels: ✨ Feature

#100 bugfix: 회원가입 페이지 버그 수정
  package.json
  src/@types/mypage.types.ts
  src/apis/mypage.ts
  src/components/MyPage/MyPageComment/MyPagePlaceReview.tsx
  src/components/MyPage/MyPageComment/MyPageTripRecordReview.tsx
  src/components/MyPage/MyPagePlan/MyPagePlan.tsx
  src/components/MyPage/MyPagePlan/MyPagePlanItem.styles.ts
  src/components/MyPage/MyPagePlan/MyPagePlanItem.tsx
  src/components/MyPage/MyPagePlan/MyPagePlanItem.types.ts
  src/components/MyPage/MyPagePopMenu/MyPagePopMenu.tsx
  src/components/MyPage/MyPagePopMenu/MyPagePopMenu.types.ts
  src/components/MyPage/MyPageReview/MyPageReview.tsx
  src/components/MyPage/MyPageReview/MyPageReviewItem.tsx
  src/components/MyPage/MyPageReview/MyPageReviewItem.types.ts
  src/components/MyPage/MyPageTopProfile/MyPageTopProfile.tsx
  src/components/auth/SignInEmailForm/SignInEmailForm.tsx
  src/components/auth/SignUpForm/SignUpForm.tsx
  src/components/common/TextField/EmailInput/EmailInput.tsx
  src/pages/MyPage/EditProfile.tsx
  src/pages/MyPage/TripPoint.tsx
  src/utils/dateDiff.ts
  yarn.lock
Labels: 🐞 BugFix

#94 feat: 홈/검색 api 연결 (2차)
  src/apis/home.ts
  src/apis/search.ts
  src/components/Creator/CreatorMore/CreatorMore.tsx
  src/components/Home/HomeCreator/HomeCreator.tsx
  src/components/Home/HomeCreator/HomeCreator.types.ts
  src/components/Home/HomeCreator/HomeCreatorPost.tsx
  src/components/Home/HomeShorts/HomeShorts.tsx
  src/components/Search/SearchCreator/SearchCreator.styles.ts
  src/components/Search/SearchCreator/SearchCreator.tsx
  src/components/Search/SearchNon/SearchNon.tsx
  src/components/common/Creator/Creator.tsx
  src/components/common/Creator/Creator.types.ts
  src/components/common/Shorts/Shorts.tsx
  src/components/common/Shorts/Shorts.types.ts
  src/components/common/Shorts/ShortsSwiper.tsx
  src/components/common/Spots/Spots.tsx
  src/components/common/Spots/Spots.types.ts
  src/components/common/Spots/SpotsSwiper.tsx
  src/pages/Search/SearchAll.tsx
Labels: ✨ Feature, 📬 API

#96 feat: 여행지 리뷰 댓글, 대댓글, 좋아요 기능 구현
  src/@types/place.ts
  src/App.tsx
  src/apis/place.ts
  src/components/MyPage/MyPageNoti/MyPageNoti.types.ts
  src/components/MyPage/MyPageNoti/MyPageNotiItem.types.ts
  src/components/common/ActionsModal/ActionsModal.styles.ts
  src/components/common/ActionsModal/ActionsModal.tsx
  src/components/common/ActionsModal/ActionsModal.types.ts
  src/components/common/Comment/Comment.styles.ts
  src/components/common/Comment/Comment.tsx
  src/components/common/Comment/Comment.types.ts
  src/components/common/ReviewWrite/ReviewWrite.tsx
  src/components/common/TripRecordReviewCard/TripRecordReviewCard.tsx
  src/components/common/index.ts
  src/constants/MyPage/tripRecord.ts
  src/pages/DetailFeed/ReviewComment/ReviewComment.styles.ts
  src/pages/DetailFeed/ReviewComment/ReviewComment.tsx
  src/pages/DetailFeed/Reviews/Reviews.tsx
  src/pages/Search/SearchNons.tsx
  src/pages/Trip/TripDetail/TripDetail.tsx
  src/pages/Trip/TripRecordReview/TripRecordReviewWrite.tsx
Labels: ✨ Feature

#107 fix: 맡은부분 빌드 에러 해결
  src/apis/mypage.ts
  src/components/MyPage/MyPageComment/MyPageTripRecordReview.tsx
  src/components/MyPage/MyPageWishList/MyPageWishList.tsx
  src/components/MyPage/MyPageWishList/MyPageWishListMore.tsx
  src/components/common/Spots/Spots.tsx
  src/components/common/Spots/Spots.types.ts
  src/components/common/Spots/SpotsSwiper.tsx
  src/constants/MyPage/wishlist.ts
Labels: 🐞 BugFix

#109 Fix: 작업 부분 빌드 에러 해결
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlan.tsx
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlanRecord.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddPlace/TripPlanPlaceModal/TripPlanPlaceModal.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddPlace/TripPlanPlaceModal/TripPlanPlaceModal.types.ts
  src/pages/Trip/TripPlan/TripFormDataContext.tsx
Labels: 🐞 BugFix

#110 Fix: build 에러 해결
  .eslintrc.cjs
  src/apis/search.ts
  src/components/Creator/CreatorDetail/CreatorDetail.tsx
  src/components/Creator/CreatorInfo/CreatorInfo.styles.ts
  src/components/Creator/CreatorInfo/CreatorInfo.tsx
  src/components/Creator/CreatorMore/CreateMore.types.ts
  src/components/Creator/CreatorMore/CreatorMore.tsx
  src/components/Creator/CreatorProfile/CreatorProfile.tsx
  src/components/Home/HomeCreator/HomeCreator.types.ts
  src/components/Home/HomeCreator/HomeCreatorPost.tsx
  src/components/Home/HomeMD/HomeMD.tsx
  src/components/Home/HomeMD/HomeMDChoice.tsx
  src/components/Search/SearchCreator/SearchCreator.tsx
  src/components/Search/SearchCreator/SearchCreator.types.ts
  src/components/Search/SearchCreator/SearchCreatorShorts.tsx
  src/pages/Creator/CreatorDetails.tsx
  src/pages/Home/Home.tsx
Labels: 🐞 BugFix, 📬 API

#113 fix: 배포 에러 수정
  src/components/common/Review/Review.tsx
Labels: 🐞 BugFix

#115 fix: Mixed content 에러 해결
  index.html
Labels: 🌏 Deploy, 🐞 BugFix

#112 feat: 마이페이지 알림 기능 추가
  src/@types/mypage.types.ts
  src/apis/auth.ts
  src/apis/mypage.ts
  src/components/MyPage/MyPageNoti/MyPageNoti.tsx
  src/components/MyPage/MyPageNoti/MyPageNotiItem.tsx
  src/components/MyPage/MyPageNoti/MyPageNotiItem.types.ts
  src/components/MyPage/MyPageWishList/MyPageWishList.tsx
  src/components/MyPage/MyPageWishList/MyPageWishList.utils.ts
  src/components/MyPage/MyPageWishList/MyPageWishListMore.tsx
  src/components/common/Spots/Spots.tsx
  src/components/common/Spots/Spots.types.ts
  src/components/common/Spots/SpotsSwiper.tsx
  src/constants/MyPage/notification.ts
Labels: ✨ Feature

#125 fix: 온보딩 버그 수정
  src/pages/Auth/SignIn.tsx
Labels: 🐞 BugFix

#126 feat: 여행 후기 리스트 무한 스크롤 기능 구현, Spinner 구현
  package.json
  src/apis/trip-records.ts
  src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx
  src/components/Trip/TripList/CardList/CardList.tsx
  src/components/Trip/TripList/CardList/CardList.types.ts
  src/components/common/Spinners/Spinners.styles.ts
  src/components/common/Spinners/Spinners.tsx
  src/components/common/index.ts
  src/pages/DetailFeed/Reviews/Reviews.tsx
  src/pages/Trip/TripDetail/TripDetail.tsx
  src/pages/Trip/TripList/TripList.tsx
  yarn.lock
Labels: ✨ Feature

#128 feat: 쇼츠 갤러리, 여행지 갤러리, 여행지 리스트 페이지 무한 스크롤 기능
  public/backArrowWhite.svg
  public/mark.svg
  src/@types/cityFeed.types.ts
  src/@types/touristSpotFeed.types.ts
  src/apis/detailfeed.ts
  src/apis/listpage.ts
  src/components/DetailFeed/DetailFeedShorts/DetailFeedShorts.styles.ts
  src/components/DetailFeed/DetailFeedShorts/DetailFeedShorts.tsx
  src/components/DetailFeed/Gallery/CityGallery.tsx
  src/components/DetailFeed/Gallery/Gallery.types.ts
  src/components/DetailFeed/Gallery/SpotGallery.tsx
  src/components/DetailFeed/HotPlace/HotPlace.tsx
  src/components/DetailFeed/Information/Information.types.ts
  src/components/DetailFeed/Information/SpotInformation.tsx
  src/components/DetailFeed/Weather/Weather.type.ts
  src/components/DetailFeed/index.ts
  src/components/Map/Map.tsx
  src/components/Search/SearchCreator/SearchCreator.types.ts
  src/components/common/Modal/ShortsModal.styles.ts
  src/components/common/Modal/ShortsModal.tsx
  src/components/common/Modal/ShortsModal.types.ts
  src/components/common/Navigation/FeedNav.tsx
  src/components/common/Navigation/FeedNav.types.ts
  src/components/common/Navigation/ShortsNav.styles.ts
  src/components/common/Navigation/ShortsNav.tsx
  src/components/common/Shorts/Shorts.tsx
  src/components/common/Shorts/Shorts.types.ts
  src/components/common/Shorts/ShortsSwiper.tsx
  src/hooks/DetailFeed/useDetailFeedQuery.ts
  src/pages/DetailFeed/City/City.tsx
  src/pages/DetailFeed/GalleryList/CityGalleryList.tsx
  src/pages/DetailFeed/GalleryList/SpotGalleryList.tsx
  src/pages/DetailFeed/ShortsList/ShortsList.tsx
  src/pages/DetailFeed/SpotList/SpotList.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
Labels: ✨ Feature

#130 feat: 여행 후기 스켈레톤 UI 구현
  src/App.tsx
  src/components/Trip/TripDetail/Introduction/Introduction.tsx
  src/components/Trip/TripDetail/Introduction/IntroductionSkeleton.tsx
  src/components/Trip/TripDetail/MainCarousel/MainCarousel.tsx
  src/components/Trip/TripDetail/TripContents/TripContents.styles.ts
  src/components/Trip/TripDetail/TripContents/TripContents.tsx
  src/components/Trip/TripDetail/TripContents/TripContents.types.ts
  src/components/Trip/TripDetail/TripContents/TripContentsSkeleton.tsx
  src/components/Trip/TripHome/ShortsCarousel/ShortCarouselSkeleton.tsx
  src/components/Trip/TripHome/TripCard/TripCard.tsx
  src/components/Trip/TripHome/TripCarousel/TripCarouselSkeleton.tsx
  src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx
  src/components/Trip/TripList/CardList/CardListSkeleton.tsx
  src/components/Trip/index.ts
  src/pages/Trip/TripDetail/TripDetail.tsx
  src/pages/Trip/TripList/TripList.tsx
Labels: ✨ Feature, 🎨 Style

#133 feat: 여행지 리뷰 스켈레톤 UI 구현
  src/App.tsx
  src/components/DetailFeed/PlaceReview/PlaceReview.tsx
  src/components/Map/Map.tsx
  src/components/Trip/TripDetail/Maps/Maps.tsx
  src/components/common/PlaceReviewCard/PlaceReviewCard.styles.ts
  src/pages/DetailFeed/ReviewComment/ReviewComment.tsx
  src/pages/DetailFeed/ReviewComment/ReviewCommentSkeleton.styles.ts
  src/pages/DetailFeed/ReviewComment/ReviewCommentSkeleton.tsx
  src/pages/DetailFeed/Reviews/Reviews.tsx
  src/pages/DetailFeed/Reviews/ReviewsSkeleton.styles.ts
  src/pages/DetailFeed/Reviews/ReviewsSkeleton.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
Labels: ✨ Feature, 🎨 Style

#135 feat: 상세 피드 검색 페이지 기능 구현
  src/@types/touristSpotFeed.types.ts
  src/App.tsx
  src/apis/listpage.ts
  src/apis/spotfeed.ts
  src/components/DetailFeed/Gallery/Gallery.types.ts
  src/components/DetailFeed/SearchedSpot/SearchedSpot.styles.ts
  src/components/DetailFeed/SearchedSpot/SearchedSpot.tsx
  src/components/DetailFeed/SearchedSpot/SearchedSpot.types.ts
  src/components/DetailFeed/SearchedSpot/SpotDescription.styles.ts
  src/components/DetailFeed/SearchedSpot/SpotDescription.tsx
  src/components/DetailFeed/Weather/Weather.type.ts
  src/components/DetailFeed/index.ts
  src/components/common/Navigation/SpotListNav.tsx
  src/pages/DetailFeed/SpotList/SpotList.styles.ts
  src/pages/DetailFeed/SpotList/SpotList.tsx
  src/pages/DetailFeed/SpotSearch/SpotSearch.styles.ts
  src/pages/DetailFeed/SpotSearch/SpotSearch.tsx
Labels: ✨ Feature

#138 feat: 여행지 상세페이지 리뷰 구현, 여행지 리뷰 리스트 무한스크롤 구현
  src/@types/place.ts
  src/apis/place.ts
  src/components/DetailFeed/PlaceReview/PlaceReview.styles.ts
  src/components/DetailFeed/PlaceReview/PlaceReview.tsx
  src/components/DetailFeed/PlaceReviews/PlaceReviews.styles.ts
  src/components/DetailFeed/PlaceReviews/PlaceReviews.tsx
  src/components/DetailFeed/PlaceReviews/PlaceReviews.types.ts
  src/components/DetailFeed/index.ts
  src/pages/DetailFeed/ReviewComment/ReviewComment.tsx
  src/pages/DetailFeed/Reviews/Reviews.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
  src/pages/Trip/TripDetail/TripDetail.tsx
Labels: ✨ Feature

#140 feat: 여행 일정 메인 페이지 쇼츠 모달 구현, Floating 버튼 링크 연결, 여행 일정 복사하기 링크 연결
  src/@types/trip-records.types.ts
  src/App.tsx
  src/components/Trip/TripDetail/TripDescription/TripDescription.tsx
  src/components/Trip/TripHome/FloatingButton/FloatingButton.tsx
  src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.tsx
  src/components/common/Shorts/ShortsSwiper.tsx
  src/utils/videoKey.ts
Labels: ✨ Feature

#145 refactor: 여행 메인 페이지 쇼츠 수정
  src/components/Trip/TripHome/ShortCard/ShortCard.tsx
  src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.tsx
  src/pages/DetailFeed/ShortsList/ShortsList.tsx
Labels: 🔨 Refactor

#146 Feat: key에러 삭제
  src/components/Home/HomeHotplace/HomeHotplace.tsx
  src/pages/Search/SearchTag.tsx
  src/pages/Search/SearchTagExpense.tsx
Labels: 🐞 BugFix

#148 refactor: 환율 양뱡향 로직 구현
  src/@types/cityFeed.types.ts
  src/components/DetailFeed/ExchangeRate/ExchangeRate.styles.ts
  src/components/DetailFeed/ExchangeRate/ExchangeRate.tsx
  src/components/Home/HomeAllCity/HomeCities.tsx
  src/components/Home/HomeCreator/HomeCreator.tsx
  src/components/Home/HomeHotplace/HomeHotplace.tsx
  src/components/Home/HomeShorts/HomeShorts.tsx
  src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.tsx
  src/pages/DetailFeed/City/City.tsx
  src/pages/Search/Search.styles.ts
  src/pages/Search/Search.tsx
  src/pages/Search/Search.types.ts
  src/pages/Search/SearchNons.tsx
  src/pages/Search/SearchTag.tsx
  src/pages/Search/SearchTagExpense.tsx
Labels: 🔨 Refactor

#149 feat: 여행지 구글 맵 기능 구현
  public/ColorLandmark.svg
  public/ColorMyLocation.svg
  public/ColorRestraunt.svg
  public/Landmark.svg
  public/Restraunt.svg
  public/RetrySearch.svg
  public/googleMarkerIcon.png
  public/myLocation.svg
  public/myPostion.svg
  public/pinDefault.svg
  public/pinPress.svg
  src/@types/tripmap.ts
  src/App.tsx
  src/apis/tripmap.ts
  src/components/common/Navigation/SpotListNav.tsx
  src/constants/DetailFeed/Map.ts
  src/pages/DetailFeed/SpotList/SpotList.tsx
  src/pages/DetailFeed/TripMap.tsx
  src/pages/DetailFeed/TripMap/CurrentLocation/CurrentLocation.styles.ts
  src/pages/DetailFeed/TripMap/CurrentLocation/CurrentLocation.tsx
  src/pages/DetailFeed/TripMap/Gmap/Gmap.tsx
  src/pages/DetailFeed/TripMap/MapSpotInfoBox/MapDefaultSpot.tsx
  src/pages/DetailFeed/TripMap/MapSpotInfoBox/MapGoogleSpot.tsx
  src/pages/DetailFeed/TripMap/MapSpotInfoBox/MapSpotInfoBox.styles.ts
  src/pages/DetailFeed/TripMap/SearchButton/SearchButton.styles.ts
  src/pages/DetailFeed/TripMap/SearchButton/SearchButton.tsx
  src/pages/DetailFeed/TripMap/SpotCategory/SpotCategory.styles.ts
  src/pages/DetailFeed/TripMap/SpotCategory/SpotCategory.tsx
  src/pages/DetailFeed/TripMap/TripMap.styles.ts
  src/pages/DetailFeed/TripMap/TripMap.tsx
  src/pages/DetailFeed/index.ts
Labels: ✨ Feature

#151 chore: 구글 장소 이미지 구글 이미지로 변경
  public/images/googleLogo.png
  public/noImage.png
  src/@types/tripmap.ts
  src/apis/tripmap.ts
  src/components/DetailFeed/HotPlace/HotPlace.tsx
  src/components/DetailFeed/Information/Information.types.ts
  src/components/DetailFeed/Information/SpotInformation.styles.ts
  src/components/DetailFeed/Information/SpotInformation.tsx
  src/constants/DetailFeed/Map.ts
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
  src/pages/DetailFeed/TripMap/Gmap/Gmap.tsx
  src/pages/DetailFeed/TripMap/MapSpotInfoBox/MapGoogleSpot.tsx
  src/pages/DetailFeed/TripMap/TripMap.tsx
Labels: 🥰 Accessibility

#156 Fix: 여행 계획 POST시 에러 수정
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlan.tsx
Labels: 🐞 BugFix

#155 fix: 미구현 페이지 링크 삭제
  src/components/MyPage/MyPagePlan/MyPagePlanItem.tsx
  src/components/MyPage/MyPagePopMenu/MyPagePopMenu.tsx
Labels: 🐞 BugFix

#158 Feature/#136
  src/@types/tripmap.ts
  src/apis/tripmap.ts
  src/constants/DetailFeed/Map.ts
  src/pages/DetailFeed/TripMap/MapSpotInfoBox/MapGoogleSpot.tsx
  src/pages/DetailFeed/TripMap/TripMap.tsx
Labels: ✨ Feature

#159 fix: 캐싱시간, 박수 계산 수정
  src/components/MyPage/MyPageComment/MyPagePlaceReview.tsx
  src/components/MyPage/MyPageComment/MyPageTripRecordReview.tsx
  src/components/MyPage/MyPagePlan/MyPagePlan.tsx
  src/components/MyPage/MyPagePlan/MyPagePlanItem.tsx
  src/components/MyPage/MyPageReview/MyPageReview.tsx
Labels: 🐞 BugFix

#160 Fix: 태그 미입력시 null값 기본 지정
  src/@types/trip-alldata.types.ts
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlan.tsx
  src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlan.types.ts
  src/components/Trip/TripPlan/TripPlanPostingPlanRecord/TripPlanPostingPlanRecord.tsx
  src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddTags/TripPlanAddTags.types.ts
Labels: 🐞 BugFix
