Repository TripComeTrue/TripComeTrue_FE, pull requests merged in 2024-02, with the labels that each got.

#166 refactor: 여행지 리뷰 에러 핸들링 및 Suspense와 ErrorBoundary 적용
  package.json
  src/@types/place.ts
  src/@types/response.types.ts
  src/apis/place.ts
  src/components/DetailFeed/CommentList/CommentList.styles.ts
  src/components/DetailFeed/CommentList/CommentList.tsx
  src/components/DetailFeed/CommentList/CommentList.types.ts
  src/components/DetailFeed/ReviewCommentMain/ReviewCommentMain.tsx
  src/components/DetailFeed/ReviewCommentMain/ReviewCommentMain.types.ts
  src/components/DetailFeed/ReviewDetail/ReviewDetail.styles.ts
  src/components/DetailFeed/ReviewDetail/ReviewDetail.tsx
  src/components/DetailFeed/ReviewDetail/ReviewDetail.types.ts
  src/components/DetailFeed/ReviewList/ReviewList.tsx
  src/components/DetailFeed/index.ts
  src/components/common/ReviewWrite/ReviewWrite.tsx
  src/main.tsx
  src/pages/DetailFeed/PlaceReview/PlaceReviewEdit.tsx
  src/pages/DetailFeed/PlaceReview/PlaceReviewWrite.tsx
  src/pages/DetailFeed/ReviewComment/ReviewComment.tsx
  src/pages/DetailFeed/Reviews/Reviews.tsx
  src/styles/index.css
  yarn.lock
Labels: 🔨 Refactor

#170 refactor: 여행 메인, 여행 상세페이지 에러 핸들링 및 Suspense와 ErrorBoundary 적용
  src/@types/trip-records.types.ts
  src/apis/place.ts
  src/apis/trip-records.ts
  src/components/Trip/TripDetail/Introduction/Introduction.tsx
  src/components/Trip/TripDetail/Introduction/Introduction.types.ts
  src/components/Trip/TripDetail/MainCarousel/MainCarousel.tsx
  src/components/Trip/TripDetail/Maps/Maps.tsx
  src/components/Trip/TripDetail/OtherTripRecords/OtherTripRecords.styles.ts
  src/components/Trip/TripDetail/OtherTripRecords/OtherTripRecords.tsx
  src/components/Trip/TripDetail/OtherTripRecords/OtherTripRecordsSkeleton.tsx
  src/components/Trip/TripDetail/ReviewAlert/ReviewAlert.styles.ts
  src/components/Trip/TripDetail/ReviewAlert/ReviewAlert.tsx
  src/components/Trip/TripDetail/ReviewAlert/ReviewAlertSkeleton.styles.ts
  src/components/Trip/TripDetail/ReviewAlert/ReviewAlertSkeleton.tsx
  src/components/Trip/TripDetail/TripComment/TripComment.styles.ts
  src/components/Trip/TripDetail/TripComment/TripComment.tsx
  src/components/Trip/TripDetail/TripContents/TripContents.tsx
  src/components/Trip/TripDetail/TripContents/TripContents.types.ts
  src/components/Trip/TripDetail/TripDescription/TripDescription.tsx
  src/components/Trip/TripDetail/TripDetailMain/TripDetailMain.styles.ts
  src/components/Trip/TripDetail/TripDetailMain/TripDetailMain.tsx
  src/components/Trip/TripDetail/TripDetailMain/TripDetailMainSkeleton.tsx
  src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx
  src/components/Trip/TripHome/TripHomeBody/TripHomeBodySkeleton.tsx
  src/components/Trip/index.ts
  src/pages/Trip/TripDetail/TripDetail.tsx
  src/pages/Trip/TripHome/TripHome.tsx
Labels: 🔨 Refactor

#168 refactor: 도시/ 여행지 상세 피드 라우팅 재설정
  src/@types/cityFeed.types.ts
  src/@types/touristSpotFeed.types.ts
  src/App.tsx
  src/apis/detailfeed.ts
  src/apis/listpage.ts
  src/apis/tripmap.ts
  src/components/DetailFeed/DetailFeedShorts/DetailFeedShorts.tsx
  src/components/DetailFeed/ExchangeRate/ExchangeRate.tsx
  src/components/DetailFeed/Gallery/CityGallery.tsx
  src/components/DetailFeed/Gallery/SpotGallery.tsx
  src/components/DetailFeed/HotPlace/HotPlace.tsx
  src/components/DetailFeed/Information/CityInformation.tsx
  src/components/DetailFeed/Information/Information.types.ts
  src/components/DetailFeed/Information/SpotInformation.tsx
  src/components/DetailFeed/RecommendSpot/RecommendSpot.tsx
  src/components/DetailFeed/SearchedSpot/SearchedSpot.tsx
  src/components/DetailFeed/TopReview/CityTopReview.tsx
  src/components/DetailFeed/TopReview/SpotTopReview.tsx
  src/components/DetailFeed/Weather/Weather.tsx
  src/components/common/Navigation/FeedNav.tsx
  src/components/common/Navigation/FeedNav.types.ts
  src/components/common/Navigation/SpotListNav.tsx
  src/components/common/index.ts
  src/hooks/DetailFeed/useDetailFeedQuery.ts
  src/pages/DetailFeed/City/City.tsx
  src/pages/DetailFeed/GalleryList/CityGalleryList.tsx
  src/pages/DetailFeed/GalleryList/SpotGalleryList.tsx
  src/pages/DetailFeed/ShortsList/ShortsList.tsx
  src/pages/DetailFeed/SpotList/SpotList.tsx
  src/pages/DetailFeed/SpotSearch/SpotSearch.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
  src/pages/DetailFeed/TripMap/TripMap.tsx
Labels: 🔨 Refactor

#180 refactor: 여행 상세 페이지 스켈레톤 및 에러바운더리 추가
  src/components/DetailFeed/Information/SpotInformationSkeleton.tsx
  src/components/DetailFeed/index.ts
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
Labels: ✨ Feature, 🔨 Refactor

#181 refactor: 피드 네브바 리팩터링
  src/components/common/Navigation/FeedNav.styles.ts
  src/components/common/Navigation/FeedNav.tsx
  src/components/common/Navigation/FeedNavSkeleton.tsx
  src/components/common/index.ts
  src/pages/DetailFeed/City/City.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
Labels: ✨ Feature, 🔨 Refactor

#184 deploy: 리팩토링 작업 후 배포
  src/@types/cityFeed.types.ts
  src/@types/touristSpotFeed.types.ts
  src/App.tsx
  src/apis/detailfeed.ts
  src/apis/spotfeed.ts
  src/components/DetailFeed/Banner/Banner.tsx
  src/components/DetailFeed/DetailFeedShorts/DetailFeedShorts.styles.ts
  src/components/DetailFeed/DetailFeedShorts/DetailFeedShorts.tsx
  src/components/DetailFeed/DetailFeedShorts/DetailFeedShortsSkeleton.tsx
  src/components/DetailFeed/ExchangeRate/ExchangeRate.styles.ts
  src/components/DetailFeed/ExchangeRate/ExchangeRate.tsx
  src/components/DetailFeed/ExchangeRate/ExchangeRateSkeleton.tsx
  src/components/DetailFeed/Gallery/CityGallery.tsx
  src/components/DetailFeed/Gallery/Gallery.styles.ts
  src/components/DetailFeed/Gallery/GallerySkeleton.tsx
  src/components/DetailFeed/Gallery/SpotGallery.tsx
  src/components/DetailFeed/HotPlace/HotPlace.styles.ts
  src/components/DetailFeed/HotPlace/HotPlace.tsx
  src/components/DetailFeed/HotPlace/HotPlaceSkeleton.tsx
  src/components/DetailFeed/Information/CityInformation.styles.ts
  src/components/DetailFeed/Information/CityInformation.tsx
  src/components/DetailFeed/Information/CityInformationSkeleton.tsx
  src/components/DetailFeed/Information/Information.types.ts
  src/components/DetailFeed/Information/SpotInformation.tsx
  src/components/DetailFeed/Information/SpotInformationSkeleton.tsx
  src/components/DetailFeed/PlaceReviews/PlaceReviews.tsx
  src/components/DetailFeed/PlaceReviews/PlaceReviews.types.ts
  src/components/DetailFeed/RecommendSpot/RecommendSpot.tsx
  src/components/DetailFeed/TopReview/CityTopReview.tsx
  src/components/DetailFeed/TopReview/SpotTopReview.tsx
  src/components/DetailFeed/TopReview/TopReview.styles.ts
  src/components/DetailFeed/TopReview/TopReviewSkeleton.tsx
  src/components/DetailFeed/Weather/Weather.styles.ts
  src/components/DetailFeed/Weather/Weather.tsx
  src/components/DetailFeed/Weather/WeatherSkeleton.tsx
  src/components/DetailFeed/index.ts
  src/components/Home/HomeAllCity/HomeAllCity.tsx
  src/components/Home/HomeAllCity/HomeCities.tsx
  src/components/Home/HomeAllCity/HomeCountryItem.tsx
  src/components/Home/HomeAllCity/HomeKoreaCityItem.tsx
  src/components/Home/HomeHotplace/HomeHotplace.tsx
  src/components/common/Navigation/FeedNav.styles.ts
  src/components/common/Navigation/FeedNav.tsx
  src/components/common/Navigation/FeedNav.types.ts
  src/components/common/Navigation/FeedNavSkeleton.tsx
  src/components/common/index.ts
  src/constants/city.ts
  src/pages/DetailFeed/City/City.tsx
  src/pages/DetailFeed/TouristSpot/TouristSpot.tsx
Labels: 🌏 Deploy
